version: 1
updates:
  # Enable version updates for npm
  - package-ecosystem: "rust:cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:00"
    reviewers:
      - "maciej-makowski"
